name: SkyEssentials
version: '${project.version}'
main: me.jxstkirito.skyessentials.SkyEssentials
api-version: '1.20'
commands:
  fly:
        permission: SkyEssentials.fly
        description: enables fly
        usage: /<command>
  die:
    permission: SkyEssentials.die
    description: kills you
    usage: /<command>
    aliases:
      - killme
  heal:
    permission: SkyEssentials.heal
    description: heals you
    usage: /<command>
    aliases:
      - healme
  gm:
    permission: SkyEssentials.gm
    description: switch gamemodes
    usage: /<command>
    aliases:
      - gamemode
  god:
    permission: SkyEssentials.god
    description: become invincible
    usage: /<command>
    aliases:
      - unsterblich
      - gott
  feed:
    permission: SkyEssentials.feed
    description: you get feeded
    usage: /<command>
    aliases:
      - feedme
      - nohunger

