name: SkyEssentials
version: '${project.version}'
main: me.jxstkirito.skyessentials.SkyEssentials
api-version: '1.20'
commands:
  heal:
    description: heals you
    usage: /<command>
    aliases:
      - healme
  gm:
    description: switch gamemodes
    usage: /<command>
    aliases:
      - gamemode
  trollmenu:
    description: open a troll menu to have fun with other players
    usage: /<command>
  god:
    description: become invincible
    usage: /<command>
    aliases:
      - unsterblich
      - gott
  feed:
    description: you get feeded
    usage: /<command>
    aliases:
      - feedme
      - nohunger

