name: SkyEssentials
version: '${project.version}'
main: me.jxstkirito.skyessentials.SkyEssentials
api-version: '1.20'
commands:
  god:
    description: become invincible
    usage: /<command>
    aliases:
      - unsterblich
      - gott
  feed:
    description: you get feeded
    usage: /<command>
    aliases:
      - feedme
      - nohunger

